### ISSUE TITLE
Lỗi khi gửi email, sử dụng smtp yandex

### ISSUE THREAD

**Issue by thanhchunghti** [tdfoss/lynx#101]
Em dùng smtp của yandex. Khi cấu hình bên site khác và gửi bằng module Liên hệ thì bình thường.

Nhưng với lynx gửi qua chức năng email bị báo lỗi. Nhờ anh xem thử.

![Capture](https://user-images.githubusercontent.com/17638740/56255374-ce3b8180-60ee-11e9-80be-eafdeebad26a.PNG)

![Capture2](https://user-images.githubusercontent.com/17638740/56255376-ced41800-60ee-11e9-876d-e7ffa6f473e9.PNG)

**Comment by mynukeviet** [comment]
Nếu được gửi thông tin mình thử xem sao nhé hongoctrien@tdfoss.vn

**Comment by thanhchunghti** [comment]
> Nếu được gửi thông tin mình thử xem sao nhé [hongoctrien@tdfoss.vn](mailto:hongoctrien@tdfoss.vn)

Em đã gửi mail ạ. Nhờ anh xem giúp.

**Comment by mynukeviet** [comment]
Ok chiều mình kiểm tra, kết quả sẽ phản hồi qua đây nhé
