### ISSUE TITLE
Tạo hóa đơn bị lỗi khi không thêm được dịch vụ

### ISSUE THREAD

**Issue by thanhchunghti** [tdfoss/lynx#122]
Em Tạo hóa đơn. Đến phần Hạng mục chi tiết thì không tìm ra được Dịch vụ đã thêm trong admin.

Anh em xem lại giúp ạ :D

**Comment by huuthoqt1994** [comment]
đã fix https://github.com/huuthoqt1994/lynx/commit/f551aab2edbba2105bbcc2519dbeed54028ced27
