### ISSUE TITLE
Thêm dấu phẩy ngăn cách khi điền giá 

### ISSUE THREAD

**Issue by thanhchunghti** [tdfoss/lynx#123]
Trong admin giá dịch vụ, quản lý thu chi,.. em nghĩ nên thêm dấu phẩy ngăn cách để tránh bị thừa thiếu số 0. 
Ngồi soi rất mỏi mắt và dễ nhầm lần.

**Comment by huuthoqt1994** [comment]
đã xong https://github.com/huuthoqt1994/lynx/commit/f322816ab7f4c8bba08521e4622e1324dd04d76b
