### ISSUE TITLE
invoice: tìm kiếm hóa đơn từ ngày, đến ngày

### ISSUE THREAD

**Issue by mynukeviet** [tdfoss/lynx#64]
- Tìm hóa đơn được tạo từ ngày, đến ngày
- Tìm hóa đơn đã thanh toán (có 5 trạng thái) từ ngày, đến ngày

**Comment by huuthoqt1994** [comment]
đã fix https://github.com/huuthoqt1994/lynx/commit/eaa9665541e1d665834b9bef050b58b7ccfa3bc6.

**Comment by mynukeviet** [comment]
Mặc định cần để trắng để khi tìm kiếm theo các tiêu chí khác thì ko bị ràng buộc thêm ngày tháng

![image](https://user-images.githubusercontent.com/6407361/57276253-3b797b80-70cb-11e9-9807-f747104b3651.png)
