### ISSUE TITLE
invoice: Thêm thông báo hóa đơn sắp hết hạn

### ISSUE THREAD

**Issue by mynukeviet** [tdfoss/lynx#79]
Hiện tại chỉ khi check vô Tạo tự động thì mới có thông báo, hóa đơn mô không check thì hết hạn mà không có thông báo chi hết

**Comment by huuthoqt1994** [comment]
đã xong https://github.com/huuthoqt1994/lynx/commit/ef0d578c838b459ae5615c9340932d211d365eaf

**Comment by mynukeviet** [comment]
Thông báo khác, mà hiển thị cái bảng là khác
